AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless backend for Cloud Resume Challenge

Resources:
  UpdateVisitorCountFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateVisitorCountFunction
      Handler: app.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: VisitorCount
      Environment:
        Variables:
          TABLE_NAME: VisitorCount
      Events:
        UpdateVisitorCount:
          Type: Api
          Properties:
            Path: /updatevisitorcount
            Method: GET
